/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gesa Rizky Nugraha
 */
public class Framewaktu extends javax.swing.JFrame {

    /**
     * Creates new form Framepanjang
     */
    public Framewaktu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input = new javax.swing.JTextField();
        cmb_menu = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        out1 = new javax.swing.JTextField();
        out2 = new javax.swing.JTextField();
        out3 = new javax.swing.JTextField();
        out4 = new javax.swing.JTextField();
        out5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("KALKULATOR KONVERSI SATUAN WAKTU");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Jam, Hari, Minggu, Bulan dan Tahun (Isikan satuan awal, pilih dari satuan)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Satuan Awal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Satuan Dari");

        cmb_menu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih:", "Jam", "Hari", "Minggu", "Bulan", "Tahun" }));
        cmb_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_menuActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Kesatuan");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Jam");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Hari");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Minggu");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Bulan");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tahun");

        out1.setEditable(false);

        out2.setEditable(false);

        out3.setEditable(false);

        out4.setEditable(false);

        out5.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(out4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(out3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(out5, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(out2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(input)
                                .addComponent(cmb_menu, 0, 277, Short.MAX_VALUE)
                                .addComponent(out1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(out1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(out2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(out3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(out4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(out5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_menuActionPerformed
        // TODO add your handling code here:
        String teksinput = input.getText();
        double input = Double.parseDouble(teksinput); 
        if(cmb_menu.getSelectedIndex()==0)
        {
            out1.setText(null);
            out2.setText(null);
            out3.setText(null);
            out4.setText(null);
            out5.setText(null);
        }
        if(cmb_menu.getSelectedIndex()==1)
        {
        double has1 = input * 1;
        int hasil1 = (int)has1;
        String output1 = String.valueOf(hasil1);
        out1.setText(output1);
        double has2 = input * 0.0416666666666667;
        int hasil2 = (int)has2;
        String output2 = String.valueOf(hasil2);
        out2.setText(output2);
        double has3 = input * 0.005952380952381;
        int hasil3 = (int)has3;
        String output3 = String.valueOf(hasil3);
        out3.setText(output3);
        double has4 = input * 0.0013888888888889;
        int hasil4 = (int)has4;
        String output4 = String.valueOf(hasil4);
        out4.setText(output4);
        double has5 = input * 1.144688644688645e-4;
        int hasil5 = (int)has5;
        String output5 = String.valueOf(hasil5);
        out5.setText(output5);
        }
        if(cmb_menu.getSelectedIndex()==2)
        {
        double has1 = input * 24;
        int hasil1 = (int)has1;
        String output1 = String.valueOf(hasil1);
        out1.setText(output1);
        double has2 = input * 1;
        int hasil2 = (int)has2;
        String output2 = String.valueOf(hasil2);
        out2.setText(output2);
        double has3 = input * 0.1428571428571429;
        int hasil3 = (int)has3;
        String output3 = String.valueOf(hasil3);
        out3.setText(output3);
        double has4 = input * 0.0333333333333333;
        int hasil4 = (int)has4;
        String output4 = String.valueOf(hasil4);
        out4.setText(output4);
        double has5 = input * 0.0027472527472527;
        int hasil5 = (int)has5;
        String output5 = String.valueOf(hasil5);
        out5.setText(output5);
        }
        if(cmb_menu.getSelectedIndex()==3)
        {
        double has1 = input * 168;
        int hasil1 = (int)has1;
        String output1 = String.valueOf(hasil1);
        out1.setText(output1);
        double has2 = input * 7;
        int hasil2 = (int)has2;
        String output2 = String.valueOf(hasil2);
        out2.setText(output2);
        double has3 = input * 1;
        int hasil3 = (int)has3;
        String output3 = String.valueOf(hasil3);
        out3.setText(output3);
        double has4 = input * 0.24;
        int hasil4 = (int)has4;
        String output4 = String.valueOf(hasil4);
        out4.setText(output4);
        double has5 = input * 0.02;
        int hasil5 = (int)has5;
        String output5 = String.valueOf(hasil5);
        out5.setText(output5);
        }
        if(cmb_menu.getSelectedIndex()==4)
        {
        double has1 = input * 720;
        int hasil1 = (int)has1;
        String output1 = String.valueOf(hasil1);
        out1.setText(output1);
        double has2 = input * 30;
        int hasil2 = (int)has2;
        String output2 = String.valueOf(hasil2);
        out2.setText(output2);
        double has3 = input * 4;
        int hasil3 = (int)has3;
        String output3 = String.valueOf(hasil3);
        out3.setText(output3);
        double has4 = input * 1;
        int hasil4 = (int)has4;
        String output4 = String.valueOf(hasil4);
        out4.setText(output4);
        double has5 = input * 0.0834;
        int hasil5 = (int)has5;
        String output5 = String.valueOf(hasil5);
        out5.setText(output5);
        }
        if(cmb_menu.getSelectedIndex()==5)
        {
        double has1 = input * 8736;
        int hasil1 = (int)has1;
        String output1 = String.valueOf(hasil1);
        out1.setText(output1);
        double has2 = input * 364;
        int hasil2 = (int)has2;
        String output2 = String.valueOf(hasil2);
        out2.setText(output2);
        double has3 = input * 52;
        int hasil3 = (int)has3;
        String output3 = String.valueOf(hasil3);
        out3.setText(output3);
        double has4 = input * 12;
        int hasil4 = (int)has4;
        String output4 = String.valueOf(hasil4);
        out4.setText(output4);
        double has5 = input * 1;
        int hasil5 = (int)has5;
        String output5 = String.valueOf(hasil5);
        out5.setText(output5);
        }
        
    }//GEN-LAST:event_cmb_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framewaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framewaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framewaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framewaktu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framewaktu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmb_menu;
    private javax.swing.JTextField input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField out1;
    private javax.swing.JTextField out2;
    private javax.swing.JTextField out3;
    private javax.swing.JTextField out4;
    private javax.swing.JTextField out5;
    // End of variables declaration//GEN-END:variables
}
